// Top-level build file where you can add configuration options common to all sub-projects/modules.
allprojects {
    repositories {
        google()
        mavenCentral() // Ensure mavenCentral is included
    }
}

// Task to clean the build directory
task clean(type: Delete) {
    delete rootProject.buildDir
}
